# Add configuration values here, as shown below.
braintree_merchant_id: "g3rp2pb9fvvwygx9"
braintree_public_key: "d9ft3bb2kcn9gqqg"
braintree_private_key: "9ef914cff42d2ea342fa4002423d8aa2"
plan_a_price: 5
plan_b_price: 100
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
